repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(\.idea/|\.vscode/)
      - id: end-of-file-fixer
        exclude: ^(\.idea/|\.vscode/)
      - id: check-yaml
        exclude: ^(conda/.*\.ya?ml|\.idea/|\.vscode/)
