{% set name = "enso_metrics" %}
{% set version = "1.1.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/CLIVAR-PRP/ENSO_metrics/archive/refs/tags/v{{ version }}.tar.gz
    sha256: abc17f7f48669becc7ae38aed056fbf1f9d5b92fa2788c2d772c485eaca9297e    

build:
  number: 1
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cdms2
    - cdutil
    - genutil
    - numpy
    - scipy
    - udunits2

test:
  imports:
    - EnsoMetrics.EnsoCollectionsLib
    - EnsoMetrics.EnsoComputeMetricsLib
  commands:
    - pip check
  requires:
    - pip

about:
    home: https://github.com/CLIVAR-PRP/ENSO_metrics
    license: BSD-3-Clause
    license_file: LICENSE
    summary: "Library to compute ENSO metrics"

extra:
  recipe-maintainers:
    - eguil
    - lee1043
    - acordonez
    - yyplanton
