{% set name = "ensometrics" %}
{% set version = "0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: https://github.com/eguil/Enso_metrics.git
    git_rev: master
    

build:
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cdms2
    - numpy
    - udunits2
    - genutil

test:
  command:
    - export UVCDAT_ANONYMOUS_LOG=false && python run_tests.py -v2

about:
    home:  http://github.com/eguil/Enso_metrics
    license: 'CCLRC'
    license_file: LICENSE
    summary: "Library to compute ENSO recipes"

extra:
  recipe-maintainers:
    - doutriaux1
    - eguil
    - lee1043
